# Turn on lamps at Sunset 

- alias: "Turn on lamps at sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  condition:
    condition: state
    entity_id: light.living_overhead
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.floor_lamp
    - delay: '00:00:01'
    - service: homeassistant.turn_on
      entity_id: switch.dress_lamp
    
    

