# Turns on the floor lamp with the overhead light if it's night or if 
# there is heavy cloud coverage.  

- alias: "Turns on floor lamp w/ overhead"
  trigger:
    - platform: state
      entity_id: light.living_overhead
      to: 'on'
  condition:
    condition: and
    conditions:   
      - condition: time 
        before: '23:00:00'
        after: '06:15:00' 
      - condition: or 
        conditions: 
        - condition: numeric_state
          entity_id: sensor.dark_sky_cloud_coverage
          above: 70          
        - condition: sun
          after: sunset
          after_offset: "-00:45:00"
        - condition: sun 
          before: sunrise 
          before_offset: "01:30:00"          
  action:
    - service: homeassistant.turn_on
      entity_id: switch.floor_lamp

      
# Turns off the lamp during the day only if there is lower cloud
# cloud coverage.
            
- alias: "Turns off lamp based on cloud coverage during the day."
  trigger:
    - platform: numeric_state
      entity_id: sensor.dark_sky_cloud_coverage
      below: 70
  condition: 
    - condition: sun
      after: sunrise
      after_offset: "01:31:00"     
      before: sunset
      before_offset: "-00:46:00"      
  action:    
    - service: homeassistant.turn_off
      entity_id: switch.floor_lamp

      
# Turns off the lamp when the overhead lights are turned off. 
      
- alias: "Turns off lamps w/ overhead"
  trigger:
    - platform: state
      entity_id: light.living_overhead
      to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.floor_lamp