- alias: "Pantry Light w/ Motion."
  trigger:
    - platform: state
      entity_id: sensor.pir_2 
      to: '1'
  action:
    - service: homeassistant.turn_on
      entity_id: script.timed_pantry_light